[package]
name = "ranim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ranim"
crate-type = ["cdylib"]

[dependencies]
async-channel = "2.3.1"
image = "0.25.5"
pollster = "0.4.0"
pyo3 = "0.22.0"
wgpu = "23.0.0"
