[package]
name = "ranim"
description = "An animation engine inspired by manim and JAnim"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage = "https://azurice.github.io/ranim"
readme = "README.md"
keywords = ["animation", "manim", "wgpu"]

[workspace]
members = ["packages/*", "xtasks/*"]

[workspace.package]
version = "0.1.0-alpha.5"
edition = "2024"
license = "MIT"
repository = "https://github.com/AzurIce/ranim"

[workspace.dependencies]
ranim-macros = { path = "packages/ranim-macros", version = "0.1.0-alpha.5" }

[dependencies]
ranim-macros.workspace = true
async-channel = "2.3.1"
bytemuck = { version = "1.20.0", features = ["derive"] }
env_logger = "0.11.6"
glam = { version = "0.30.0", features = ["bytemuck"] }
image = "0.25.5"
itertools = "0.14"
log = "0.4.25"
pollster = "0.4.0"
uuid = { version = "1.13.2", features = ["v4"] }
wgpu = "24.0.1"
anyhow = "1.0.95"
usvg = "0.45.0"
regex = "1.11.1"
wgpu-profiler = "0.22.0"
indicatif = "0.17.11"
color = "0.2.3"

[dev-dependencies]
rand = "0.9.0"
rand_chacha = "0.9.0"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[package.metadata.release]
pre-release-hook = ["git", "cliff", "-o", "CHANGELOG.md", "--tag", "{{version}}" ]
pre-release-replacements = [
  {file="README.md", search="ranim = .*", replace="{{crate_name}} = \"{{version}}\""},
]
