[package]
name = "ranim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# [lib]
# name = "ranim"
# crate-type = ["cdylib", "rlib"]

[dependencies]
async-channel = "2.3.1"
bezier-rs = "0.4.0"
bytemuck = { version = "1.19.0", features = ["derive"] }
glam = { version = "0.24.2", features = ["bytemuck"] }
image = "0.25.5"
itertools = "0.13.0"
pollster = "0.4.0"
# pyo3 = "0.22.0"
uuid = { version = "1.11.0", features = ["v4"] }
wgpu = "23.0.0"
