[package]
name = "ranim-macros"
description = "macros for ranim"
version.workspace = true
edition.workspace = true
license.workspace = true

repository.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0.40"
syn = { version = "2.0.104", features = ["full"] }
# darling = "0.20.10"
# heck = "0.5.0"
proc-macro-crate = "3.3.0"
proc-macro2 = "1.0.95"
# paste = "1.0.15"

[package.metadata.release]
tag = false
