[package]
name = "ranim-macros"
description = "macros for ranim"
version.workspace = true
edition.workspace = true
license.workspace = true

repository.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0.38"
syn = "2.0.98"
darling = "0.20.10"
heck = "0.5.0"

[package.metadata.release]
tag = false
